### ISSUE TITLE
can not install from brat and obsidian plugin market 

### ISSUE THREAD

**Issue by aiyou9** [o02c/obsidian-tab-navigator#11]
![image](https://github.com/o02c/obsidian-tab-navigator/assets/15712822/f18f0f16-160d-4fe8-a939-1bfe79b38b05)

![image](https://github.com/o02c/obsidian-tab-navigator/assets/15712822/c31eb9bc-736d-4e3e-b7db-6889f7d9f2e1)

**Comment by o02c** [comment]
@aiyou9 
Sorry.

It was due to a failed build of the source for version 0.2.7.
Fixed in the latest version (0.2.8).

**Comment by RikardSwed** [comment]
Same again. I am trying to install but it wont install. It says 1.0.0  in Obsidian.

**Comment by o02c** [comment]
Sorry, but it installs fine on my end. Could you try uninstalling and then reinstalling it?

**Comment by RikardSwed** [comment]
well, now it worked! Before it just said "failed to install". Looking forward to try the plugin now.

**Comment by RikardSwed** [comment]
Cant get it to work. I installed tab switcher as well cause I read that it was needed. However still cant get any window to open which lets me select a tab

**Comment by o02c** [comment]
I don't know about the tab switcher, but for this plugin, it can be executed from the command palette as shown in the image, or by assigning a hotkey.

![image](https://github.com/o02c/obsidian-tab-navigator/assets/164215824/3d5180a6-5990-4b1b-9234-1cb8b217c81e)

Previously, they were also trying to provide a long press of ctrl to display a list of tabs.
However, this required hacking into Obsidian's core functionality, and while it worked well locally, it did not work well as a community plugin, so I removed it.

**Comment by RikardSwed** [comment]
I choose search tabs in the command palette but nothing happens

**Comment by o02c** [comment]
I don't know if I can help you, but can you tell me what OS and Obsidian version you are using?
If possible, please let us know if you are seeing any errors in the Developer Tools console.

Also, because other plugins may be interfering with it.
Can you try to run on the new Vault?

**Comment by RikardSwed** [comment]
I am on a mac Big Sur. Latest Obsidian version 1.5.12. Tried on an empty vault same result. I choose the "search tabs" from the command pallatte and expect a pop up window to come where I can choose between the open tabs but that pop up window never shows.

**Comment by o02c** [comment]
I am on a mac Sonoma. but it not seem to occur.

Could you try update to 0.3.3 or later.
I can't be sure, but maybe it will help.

If this does not work, I am sorry, but I cannot say without seeing the error log in the developer view.(console, elements etc..)
